#!/bin/bash
set -e
. scripts/utils.sh

#CONFIGURATION 
FOLDER_BASE=$(pwd)

# set path to own public key
VBOX_KEY="${FOLDER_BASE}/vagrantkey"

# start virtual box headless mode.
# if you want see working virtual machine set
# VBOX_GUI=1
VBOX_GUI=0

## MAIN SCRIPT PART. CHANGE AT OWN RISK

function usage {
  echo "usage: $0 <32|64> [stable|testing|{x.y.z}]"
  echo "       where {x.y.z} is a valid Debian version (e.g. 7.8.0)"
  exit
}

argv=($@)

case ${argv[0]} in
    32)
        ARCH="i386"
        OS_TYPE="Debian"
    ;;
    64)
        ARCH="amd64"
        OS_TYPE="Debian_64"
    ;;
    *)
        usage ;
    ;;
esac

case ${argv[1]} in
    "stable")
        VERSION="current"
        MIRROR_DIR="release/${VERSION}"
    ;;
    "testing")
        VERSION="testing"
        MIRROR_DIR="weekly-builds"
    ;;
    *)
        if [ -z "${argv[1]}" ] ; then
            VERSION="current"
            MIRROR_DIR="release/${VERSION}"
        elif [[ ${argv[1]} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
            VERSION="${argv[1]}"
            MIRROR_DIR="archive/${VERSION}"
        else
            usage ;
        fi
    ;;
esac


BOX="debian-${VERSION}-${ARCH}"

FOLDER_ISO="${FOLDER_BASE}/iso"
FOLDER_BUILD="${FOLDER_BASE}/build"
FOLDER_VBOX="${FOLDER_BUILD}/vbox"

DEBIAN_MIRROR="cdimage.debian.org"
DEBIAN_URL="http://${DEBIAN_MIRROR}/mirror/cdimage/${MIRROR_DIR}/${ARCH}/iso-cd"
ISO_VERSION=""

VBGA_DEBIAN_PATH="/usr/share/virtualbox/VBoxGuestAdditions.iso"
VBGA_DARWIN_PATH="/Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso"

DEBUG_ECHO=0 #set sedug console output

if [[ "${VBOX_GUI}" -eq "1" ]] ; then
  VBOX_RUNTYPE=" --type gui "
else 
  VBOX_RUNTYPE=" --type headless "
fi
info "VBOX_GIU = ${VBOX_GUI}"
info "VBOX_RUNTYPE = ${VBOX_RUNTYPE}"
###############################################################################

function decho {
  if [ "${DEBUG_ECHO}" == "1" ]; then
    debugecho "$1"
  fi
}


function dep_vagrant {
    if [[ -z $(which vagrant) ]]; then
        abort "Could not find Vagrant. Aborting."
    fi
}

function dep_fakeroot {
    if [[ -z $(which fakeroot) ]]; then
        abort "Could not find fakeroot. Aborting."
    fi
}

function dep_virtualbox {
    if [[ -z $(which VBoxManage) ]]; then
        abort "Could not find VirtualBox and VBoxManage. Aborting."
    fi

    if [[ ! -f $VBGA_DEBIAN_PATH && ! -f $VBGA_DARWIN_PATH ]]; then
        abort "Could not find VirtualBox Guest Additions. Aborting."
    fi
    
    if [[ ! -f $VBOX_KEY ]] ; then  
      info "Vagrant private key not found..."
      if [[ ! -f "${FOLDER_BASE}/vagrantkey.pub" ]] ; then 
        info "Get insecure key from GITHUB..."
        wget -c "https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub" \
         -O "${FOLDER_BASE}/vagrantkey.pub"
      fi
      VBOX_KEY="${FOLDER_BASE}/vagrantkey.pub"
    fi
}

function dep_7z {
    if [[ -z $(which 7z) ]]; then
        abort "Could not find 7z. Aborting."
    fi
}

function dep_mkisofs {
    if [[ -z $(which mkisofs || which genisoimage) ]]; then
        abort "Could not find mkisofs. Aborting."
    fi
}

###############################################################################

function clean {
    info "Cleaning build directories..."
    rm -rf "${FOLDER_BASE}"/*.box
    rm -rf "${FOLDER_BUILD}/custom"
    rm -rf "${FOLDER_BUILD}/initrd"

    info "Creating directories..."
    mkdir -p "${FOLDER_ISO}"
    mkdir -p "${FOLDER_VBOX}"
    mkdir -p "${FOLDER_BUILD}/custom"
    mkdir -p "${FOLDER_BUILD}/initrd"
}

function wait_for_shutdown {
    info "Waiting for installer..."
    while VBoxManage list runningvms | grep "${BOX}" > /dev/null; do
        sleep 10
    done
}

function get_iso_version {
  info "Try get stable version number"
  STATUSCODE="$(curl http://cdimage.debian.org/debian-cd/current/amd64/iso-cd/MD5SUMS -o /dev/null --silent --head --write-out '%{http_code}\n')";
  if [ "${STATUSCODE}" == "200" ]; then
    info 'md5sums file found'
    ISO_VERSION="$(curl -s http://cdimage.debian.org/debian-cd/current/amd64/iso-cd/MD5SUMS | grep 'netinst.iso' | grep -v 'mac' | cut -d' ' -f3 | cut -d'-' -f2)"
    BOX="debian-${ISO_VERSION}-${ARCH}"
    info "Stable version number: ${ISO_VERSION}"
  else
    abort "CANT GET MD5SUMS FILE"
  fi
}

function download_iso {
    if [ "${VERSION}" == "current" ]; then
      get_iso_version
    else
      ISO_VERSION="${VERSION}"
    fi
    
    DEBIAN_ISO_NAME="debian-${ISO_VERSION}-${ARCH}-netinst.iso"
    DEBIAN_ISO_URL="${DEBIAN_URL}/${DEBIAN_ISO_NAME}"
    DEBIAN_ISO_FILE="${FOLDER_ISO}/${DEBIAN_ISO_NAME}"

    if [ ! -f "${DEBIAN_ISO_FILE}" ]; then
        info "Downloading ${DEBIAN_ISO_NAME} from ${DEBIAN_ISO_URL} ..."
        STATUSCODE="$(curl -L ${DEBIAN_ISO_URL} -o /dev/null --silent --head --write-out '%{http_code}\n')";
        if [ "${STATUSCODE}" == "200" ]; then
          curl --progress-bar -o "${DEBIAN_ISO_FILE}" -L "${DEBIAN_ISO_URL}"
        else
          abort "File not found at server"
        fi
    fi
}

function unpack_vbox_additions {

  if [ -f $VBGA_DEBIAN_PATH ]; then
      VBOX_GUESTADDITIONS=$VBGA_DEBIAN_PATH
  else
      VBOX_GUESTADDITIONS=$VBGA_DARWIN_PATH
  fi
  
  mkdir -p "${FOLDER_BUILD}/custom/VBA"
  if [[ -f "${VBOX_GUESTADDITIONS}" ]]; then
    7z x "${VBOX_GUESTADDITIONS}" -o"${FOLDER_BUILD}/custom/VBA"
  fi  
}

function customize_iso {
    info "Unpacking ${DEBIAN_ISO_NAME}...[${DEBIAN_ISO_FILE}]"
    7z x "${DEBIAN_ISO_FILE}" -o"${FOLDER_BUILD}/custom" > /dev/null

    info "Grant write permission..."
    chmod -R u+w "${FOLDER_BUILD}/custom"

    info "Customizing ISO files..."
    FOLDER_INSTALL=$(ls -1 -d "${FOLDER_BUILD}/custom/install."* | sed 's/^.*\///')
    cp -r "${FOLDER_BUILD}/custom/${FOLDER_INSTALL}/"* "${FOLDER_BUILD}/custom/install/"

    decho " -- Copy preseed.cfg to initrd"
    pushd "${FOLDER_BUILD}/initrd"
        gunzip -c "${FOLDER_BUILD}/custom/install/initrd.gz" | $(which fakeroot) cpio -id
        cp "${FOLDER_BASE}/config/preseed.cfg" "${FOLDER_BUILD}/initrd/preseed.cfg"
        find . | $(which fakeroot) cpio --create --format='newc' | gzip > "${FOLDER_BUILD}/custom/install/initrd.gz"
    popd

    decho " -- Copy bootstrap, poststrap, initserofree scripts to custom image" 
    cp "${FOLDER_BASE}/scripts/poststrap.sh" "${FOLDER_BUILD}/custom/"
    cp "${FOLDER_BASE}/scripts/bootstrap.sh" "${FOLDER_BUILD}/custom/"
    cp "${FOLDER_BASE}/scripts/initzerofree.sh" "${FOLDER_BUILD}/custom/"
    
    ## add custom apps script
    cp "${FOLDER_BASE}/scripts/custom_apps.sh" "${FOLDER_BUILD}/custom/"
    cp "${FOLDER_BASE}/config/isolinux.cfg" "${FOLDER_BUILD}/custom/isolinux/"

    decho " -- copy vagrantkey"	
    cp "${VBOX_KEY}" "${FOLDER_BUILD}/custom/vagrantkey.pub"

    info "Setting permissions on bootstrap scripts..."
    chmod 755 "${FOLDER_BUILD}/custom/poststrap.sh"
    chmod 755 "${FOLDER_BUILD}/custom/bootstrap.sh"
    chmod 755 "${FOLDER_BUILD}/custom/custom_apps.sh"
    
    info "Setting permissions on vagrant key..."
    chmod 755 "${FOLDER_BUILD}/custom/vagrantkey.pub"

    unpack_vbox_additions

    info "Packing ISO files..."
    MKISOFS=$(which mkisofs || which genisoimage)
    $MKISOFS -r -V "Custom Debian ${ISO_VERSION} Install CD" -cache-inodes -quiet -J -l \
        -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot \
        -boot-load-size 4 -boot-info-table -o "${FOLDER_BUILD}/custom.iso" \
        "${FOLDER_BUILD}/custom"
}

function vbox_unregister {
    if VBoxManage showvminfo "${BOX}" >/dev/null 2>/dev/null; then
        read -p "${txtred}Are you sure you want to destroy ${BOX}? ${txtrst}"
        if [ "$REPLY" == "y" ]; then
            VBoxManage unregistervm "${BOX}" --delete > /dev/null
            if [ $? -ne 0 ]; then
                abort "Failed to destroy ${BOX}. Aborting."
            fi
        else
            abort "VM ${BOX} already exist. Aborting."
        fi
    fi
}

function vbox_create_vm {
    info "Creating VM..."
    VBoxManage createvm --name "${BOX}" --ostype $OS_TYPE --register --basefolder "${FOLDER_VBOX}"
    VBoxManage modifyvm "${BOX}" --memory 360 --boot1 dvd --boot2 disk --boot3 none --boot4 none --vram 12 --pae off --rtcuseutc on
}

function vbox_create_storage {
    info "Creating storage devices..."
    VBoxManage storagectl "${BOX}" --name "IDE Controller" --add ide --controller PIIX4 --hostiocache on
    VBoxManage storagectl "${BOX}" --name "SATA Controller" --add sata --controller IntelAhci --portcount 1 --hostiocache off
    VBoxManage createhd --filename "${FOLDER_VBOX}/${BOX}/${BOX}.vdi" --size 40960
    VBoxManage storageattach "${BOX}" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "${FOLDER_VBOX}/${BOX}/${BOX}.vdi"
    VBoxManage storageattach "${BOX}" --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium "${FOLDER_BUILD}/custom.iso"
}

function vbox_start_and_wait_for_shutdown {
    info "Booting VM..."
    VBoxManage startvm "${BOX}" ${VBOX_RUNTYPE}
    wait_for_shutdown
}

function vbox_mount_guestadditions {
    info "Installing guest additions..."
    if [ -f $VBGA_DEBIAN_PATH ]; then
        VBOX_GUESTADDITIONS=$VBGA_DEBIAN_PATH
    else
        VBOX_GUESTADDITIONS=$VBGA_DARWIN_PATH
    fi
    VBoxManage storageattach "${BOX}" --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium "${VBOX_GUESTADDITIONS}"
}

function vagrant_package {
    info "Building Vagrant box..."
    vagrant package --base "${BOX}" --output "${BOX}.box"
}

###############################################################################

decho 'run cleaning'
clean

###

decho "check dependency vagrant"
dep_vagrant

decho "check dependency virtualbox"
dep_virtualbox

decho "check dependency 7zip"
dep_7z

decho "check dependency mkisofs | genisoimage"
dep_mkisofs

decho "check dependency fakeroot "
dep_fakeroot

###

decho "uregister previous vagrant box with same name"
vbox_unregister

###

decho "uregister previous vagrant box with same name"
download_iso

decho "uregister previous vagrant box with same name"
customize_iso

###

decho "create virtualbox image"
vbox_create_vm

decho "create storage (HDD for image)"
vbox_create_storage

decho "start and bootstrap image. wait until install done"
vbox_start_and_wait_for_shutdown

#vbox_mount_guestadditions
decho "build vbox guest addition dkms for kernel. wait until done."
vbox_start_and_wait_for_shutdown

###

decho "pack image. well done."
vagrant_package
